### ISSUE TITLE
UK phony number normalization doesn't handle cc correctly

### ISSUE THREAD

**Issue by george-semenov** [floere/phony#281] opened 2015-09-17 07:06 UTC
In reality:
```ruby
Phony.normalize('+44 7700 900853', cc: '44') == "44447700900853"
```

But I expect it to be:
```ruby
Phony.normalize('+44 7700 900853', cc: '44') == "447700900853"
```

**Comment by floere** [comment] 2015-09-17 12:28
Duplicate of #270.

**Closed by floere** 2015-09-17 12:28 UTC
