### ISSUE TITLE
1800, 1300 and 13 numbers not formatting correctly in Australia

### ISSUE THREAD

**Issue by raefa** [floere/phony#339] opened 2016-09-13 03:48 UTC
Very useful Gem. Thanks!

If you input `+611800123456` you see `01800 123 456` but you would expect `1800 123 456`.
If you input `+611300123456` you see `01300 123 456` but you would expect `1300 123 456`.
If you input `+61131234` you see `013 12 34` but you would expect `13 1234`.

**Comment by raefa** [comment] 2016-09-13 04:05
Sorry. It has been done.

**Comment by floere** [comment] 2016-09-14 18:15
Hi @raefa ! Thanks for the nice issue entry – do you think you could provide a pull request improving the rules for Australia?

**Comment by raefa** [comment] 2016-09-14 23:16
Hi @floere. Sorry. I had a look and could not work out how to do it without a massive overhaul ... and I am not skilled enough for a massive overhaul!

**Comment by floere** [comment] 2016-09-15 12:25
@raefa Ok – but when does the issue occur? When you run this?

```
ruby -e 'require "phony"; p Phony.format("611800123456", :format => :national)'
```

**Comment by raefa** [comment] 2016-09-16 02:44
@floere Yes. Exactly.

**Comment by floere** [comment] 2016-09-16 08:46
@raefa Thanks! I've added a spec here: https://github.com/floere/phony/commit/715c2713c2ce1396c78dd17b543f77d86f9901af, and a fix here: https://github.com/floere/phony/commit/7ff3ea3aa7c7e120818f979e07b72732f9bff03e Thanks again!

Released in 2.15.31 🚀

**Closed by floere** 2016-09-16 08:46 UTC

**Comment by floere** [comment] 2017-02-13 10:44
@raefa Raef, @jashank has noticed that this issue broke Australian numbers – the issue is that non-geographic phone numbers in Australia do not use a trunk code, and are generally not accessible internationally: https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia.
Now, I am wondering in what context you have encountered e.g. the number `+611800123456` – was it a natural context or a synthetic test case? I am trying to find an elegant solution to the issue at hand, and whether the example case here actually must be covered or whether it never occurs naturally. Thanks for any help 😊

**Comment by raefa** [comment] 2017-02-13 12:16
Most 1800 numbers in Australia will accept international calls. If they do you would call +61 1800 123 456.  I can't test because I'm in Australia but I am reasonably confident this is correct. 

I believe the same applies to 1300 and 13 numbers too.

**Comment by jashank** [comment] 2017-03-22 00:59
My interpretation of some (annoyingly CIC) documentation on this is that you have to explicitly request international connectivity for these numbers, and that documentation leads me to believe this is unusual.

FWIW, in the application I'm currently working on, this change breaks more phone numbers than it fixes.

**Comment by ioquatix** [comment] 2017-11-16 00:03
It's not unusual most tourist places with 1800 numbers work internationally - I've tried a handful.
